services:
  - type: web
    name: flappy-bird-app
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn website.app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
