services:
  - type: web
    name: flappy-bird-app
    runtime: python
    buildCommand: "pip install -r requirements.txt && python -m pygbag --build game/main.py && mkdir -p website/static/game && cp -r build/* website/static/game/"
    startCommand: "gunicorn website.app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
